substitutions:
  firmware_version: "1.0.0"

esphome:
  name: ascs-raumsensor
  friendly_name: ASCS Rasumsensor

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API without encryption for broader accessibility
api:

mdns:

improv_serial:

esp32_improv:
  authorizer: none
esp32_ble_tracker:

# OTA (Over-The-Air) Updates ohne Passwort für einfache Konnektivität
ota:
  - platform: esphome

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: "bme680_bus"

uart:
  id: uart_ld2450
  tx_pin: 
    number: GPIO1
  rx_pin: 
    number: GPIO3
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2450:
  id: ld2450_radar
  uart_id: uart_ld2450

binary_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    has_target:
      name: "Präsenz"
    has_moving_target:
      name: "Bewegtes Ziel"
    has_still_target:
      name: "Stehendes Ziel"

number:
  - platform: ld2450
    ld2450_id: ld2450_radar
    presence_timeout:
      name: "Auszeit"
    zone_1:
      x1:
        name: "Zone-1 X1"
      y1:
        name: "Zone-1 Y1"
      x2:
        name: "Zone-1 X2"
      y2:
        name: "Zone-1 Y2"
    zone_2:
      x1:
        name: "Zone-2 X1"
      y1:
        name: "Zone-2 Y1"
      x2:
        name: "Zone-2 X2"
      y2:
        name: "Zone-2 Y2"
    zone_3:
      x1:
        name: "Zone-3 X1"
      y1:
        name: "Zone-3 Y1"
      x2:
        name: "Zone-3 X2"
      y2:
        name: "Zone-3 Y2"

switch:
  - platform: ld2450
    ld2450_id: ld2450_radar
    multi_target:
      name: "Mehrfache Zielerfassung"

select:
  - platform: ld2450
    ld2450_id: ld2450_radar
    baud_rate:
      name: "Baud rate"
    zone_type:
      name: "Zonen Typ"

button:
  - platform: ld2450
    ld2450_id: ld2450_radar
    factory_reset:
      name: "Radar Factory Reset"
      entity_category: "config"
    restart:
      name: "Radar Neustart"
      entity_category: "config"

sensor:
  - platform: bme680
    temperature:
      name: "BME680 Temperature"
      oversampling: 16x
    pressure:
      name: "BME680 Pressure"
    humidity:
      id: "humidity"
      name: "BME680 Humidity"
    gas_resistance:
      id: "gas_resistance"
      name: "BME680 Gas Resistance"
    address: 0x77
    update_interval: 60s
  - platform: template
    name: "BME680 Indoor Air Quality"
    id: iaq
    icon: "mdi:gauge"
    # calculation: comp_gas = log(R_gas[ohm]) + 0.04 log(Ohm)/%rh * hum[%rh]
    lambda: |-
      return log(id(gas_resistance).state) + 0.04 *  id(humidity).state;
    state_class: "measurement"
  - platform: ld2450
    ld2450_id: ld2450_radar
    target_count:
      name: "Ziel Anzahl"
  - platform: ld2450
    ld2450_id: ld2450_radar
    still_target_count:
      name: "Stehende Ziel Anzahl"
  - platform: ld2450
    ld2450_id: ld2450_radar
    moving_target_count:
      name: "Bewegte Ziele Anzahl"
  - platform: ld2450
    ld2450_id: ld2450_radar
    target_1:
      x:
        name: "Ziel-1 X"
      y:
        name: "Ziel-1 Y"
      speed:
        name: "Ziel-1 Geschwindigkeit"
      angle:
        name: "Ziel-1 Winkel"
      distance:
        name: "Ziel-1 Abstand"
      resolution:
        name: "Ziel-1 Auflösung"
    target_2:
      x:
        name: "Ziel-2 X"
      y:
        name: "Ziel-2 Y"
      speed:
        name: "Ziel-2 Geschwindigkeit"
      angle:
        name: "Ziel-2 Winkel"
      distance:
        name: "Ziel-2 Abstand"
      resolution:
        name: "Ziel-2 Auflösung"
    target_3:
      x:
        name: "Ziel-3 X"
      y:
        name: "Ziel-3 Y"
      speed:
        name: "Ziel-3 Geschwindigkeit"
      angle:
        name: "Ziel-3 Winkel"
      distance:
        name: "Ziel-3 Abstand"
      resolution:
        name: "Ziel-3 Auflösung"
    zone_1:
      target_count:
        name: "Zone-1 Alle Ziele"
      still_target_count:
        name: "Zone-1 Stehende Ziele"
      moving_target_count:
        name: "Zone-1 Bewegte Ziele"
    zone_2:
      target_count:
        name: "Zone-2 Alle Ziele"
      still_target_count:
        name: "Zone-2 Stehende Ziele"
      moving_target_count:
        name: "Zone-2 Bewegte Ziele"
    zone_3:
      target_count:
        name: "Zone-3 Alle Ziele"
      still_target_count:
        name: "Zone-3 Stehende Ziele"
      moving_target_count:
        name: "Zone-3 Bewegte Ziele"

text_sensor:
  - platform: template
    name: "BME680 IAQ Classification"
    icon: "mdi:checkbox-marked-circle-outline"
    lambda: |-
      if (int(id(iaq).state) <= 50) {
        return {"Excellent"};
      }
      else if (int(id(iaq).state) <= 100) {
        return {"Good"};
      }
      else if (int(id(iaq).state) <= 150) {
        return {"Lightly polluted"};
      }
      else if (int(id(iaq).state) <= 200) {
        return {"Moderately polluted"};
      }
      else if (int(id(iaq).state) <= 250) {
        return {"Heavily polluted"};
      }
      else if (int(id(iaq).state) <= 350) {
        return {"Severely polluted"};
      }
      else if (int(id(iaq).state) <= 500) {
        return {"Extremely polluted"};
      }
      else {
        return {"unknown"};
      }
  - platform: ld2450
    ld2450_id: ld2450_radar
    version:
      name: "LD2450 Firmware"
    target_1:
      direction:
        name: "Ziel-1 Richtung"
    target_2:
      direction:
        name: "Ziel-2 Richtung"
    target_3:
      direction:
        name: "Ziel-3 Richtung"
